apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-external-app-secrets
  namespace: prd-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-external-app-secrets
