apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: performance-sync-metrics-hourly
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: stg-performance
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    name: performance-sync-metrics-hourly
    module: performance
    namespace: stg-performance
    replicas: 1
    image:
      repository: ghcr.io/tmlmobilidade/go-performance-sync-metrics-hourly
      tag: staging
      pullPolicy: Always
    service:
      port: 80
      targetPort: 5050
    ingress:
      enabled: false
    secrets:
      - stg-platform-storage
    env: []
