apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-exporter-api
  namespace: exporter-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-exporter-api
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-exporter-cleaner
  namespace: exporter-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-exporter-cleaner
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-exporter-export-drt
  namespace: exporter-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-exporter-export-drt
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-exporter-export-files
  namespace: exporter-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-exporter-export-files
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-exporter-export-gtfs-merged
  namespace: exporter-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-exporter-export-gtfs-merged
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-exporter-export-posters
  namespace: exporter-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-exporter-export-posters
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-exporter-frontend
  namespace: exporter-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-exporter-frontend
