apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-offer-api
  namespace: offer-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-offer-api
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-offer-frontend
  namespace: offer-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-offer-frontend
