apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valhalla
  namespace: flux-system
spec:
  interval: 30s
  targetNamespace: stg-valhalla
  install:
    createNamespace: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: compute/kubernetes/charts/valhalla
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    name: valhalla
    environment: stg
    pbfUrl: https://download.geofabrik.de/europe/portugal-latest.osm.pbf
    replicas: 1
    persistence:
      create: false
      existingClaim: valhalla-pvc
      mountPath: /custom_files
      size: 50Gi
      accessMode: ReadWriteOnce
      storageClassName: ""
    resources:
      requests:
        cpu: "2000m"
        memory: "4Gi"
    ingress:
      enabled: true
      path: /locations/valhalla(/|$)(.*)
      pathType: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    updateCron:
      enabled: true
      schedule: "0 4 * * *"
      timeZone: Europe/Lisbon
      mountPath: /custom_files
      pbfFileName: portugal-latest.osm.pbf
      pvcClaimName: valhalla-pvc
