apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valhalla
  namespace: valhalla
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/valhalla
      sourceRef:
        kind: HelmRepository
        name: valhalla-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    environment: stg
    image:
      repository: ghcr.io/valhalla/valhalla-scripted
      tag: latest
    service:
      type: ClusterIP
      port: 8002
    ingress:
      enabled: true
      path: /valhalla
      pathType: Prefix
      annotations: {}
    persistence:
      enabled: true
      size: 50Gi
      storageClass: ""
    pbfUrl: https://download.geofabrik.de/europe/portugal-latest.osm.pbf
    updateCron:
      enabled: true
      schedule: "0 4 * * *"
      timeZone: Europe/Lisbon
      deploymentName: valhalla
    resources:
      requests:
        cpu: "1000m"
        memory: "2Gi"
      limits:
        cpu: "4000m"
        memory: "8Gi"