apiVersion: v1
kind: PersistentVolume
metadata:
  name: stg-valhalla-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv
  csi:
    driver: blockvolume.csi.oraclecloud.com
    volumeHandle: ocid1.volume.oc1.eu-frankfurt-1.abtheljt6h6kgnkwrxm4yb66uljkp2g4wemqexiqwg4fmj6g3e3sy6qhwpqa