apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valhalla-pvc
  namespace: stg-valhalla
  labels:
    app.kubernetes.io/name: valhalla
    app.kubernetes.io/component: shared-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fss-dyn-storage
  resources:
    requests:
      storage: 50Gi
