apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valhalla-pvc
  namespace: stg-valhalla
  labels:
    app.kubernetes.io/name: valhalla
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
