apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-performance-api
  namespace: performance-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-performance-api
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-performance-frontend
  namespace: performance-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-performance-frontend
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-performance-sync-metrics-hourly
  namespace: performance-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-performance-sync-metrics-hourly
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-performance-sync-metrics-daily
  namespace: performance-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-performance-sync-metrics-daily
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-performance-sync-metrics-realtime
  namespace: performance-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-performance-sync-metrics-realtime
