apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - shared-secrets.1passworditem.yaml
  - app-secrets.1passworditem.yaml
  - api.yaml
  - frontend.yaml
  - sync-metrics-hourly.yaml
  - sync-metrics-daily.yaml
  - sync-metrics-realtime.yaml
