apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-stops-api
  namespace: stops-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-stops-api
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-stops-frontend
  namespace: stops-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-stops-frontend
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-stops-organizer
  namespace: stops-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-stops-organizer
