apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alerts-frontend
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: alerts-stg-pr-123
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    name: alerts-frontend
    module: alerts
    namespace: alerts-stg-pr-123
    replicas: 1
    image:
      repository: ghcr.io/tmlmobilidade/go-alerts-frontend
      tag: pr-123
      pullPolicy: Always
    service:
      port: 80
      targetPort: 3000
    ingress:
      enabled: true
      className: nginx
      host: pr-123.go-stg.tmlmobilidade.pt
      path: /alerts(/|$)(.*)
      pathType: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    platformSecrets:
      - stg-platform-email
      - stg-platform-storage
    env: []
