apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-locations-frontend
  namespace: prd-locations
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-locations-frontend
