apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pr-412-alerts-api
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: pr-412-alerts
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    module: alerts
    replicas: 1
    service:
      targetPort: 5050
    ingress:
      enabled: true
      path: /alerts/api(/|$)(.*)
      pathType: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      host: pr-412.go-stg.tmlmobilidade.pt
    secrets:
      - stg-platform-email
      - stg-platform-storage
    env: []
    environment: pr-412
    app: api
