apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-module-dates
  namespace: pr-412-dates
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-module-dates
