apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-performance-sync-metrics-realtime
  namespace: performance-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-performance-sync-metrics-realtime
