apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-performance-sync-metrics-realtime
  namespace: stg-performance
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/stg-app-performance-sync-metrics-realtime
