apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-offer-frontend
  namespace: stg-offer
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/stg-app-offer-frontend
