apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-api
  namespace: controller-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-api
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-coordinator
  namespace: controller-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-coordinator
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-frontend
  namespace: controller-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-frontend
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-rides-acceptor
  namespace: controller-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-rides-acceptor
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-rides-bridge
  namespace: controller-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-rides-bridge
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-rides-cleaner
  namespace: controller-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-rides-cleaner
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-rides-examiner
  namespace: controller-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-rides-examiner
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-rides-feeder
  namespace: controller-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-rides-feeder
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-rides-locker
  namespace: controller-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-rides-locker
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-sams-examiner
  namespace: controller-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-sams-examiner
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-sams-feeder
  namespace: controller-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-sams-feeder
