apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-alerts
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-apex
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-auth
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-controller
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-dates
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-locations
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-offer
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-performance
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-plans
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-stops
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-442-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
