apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-fleet-frontend
  namespace: stg-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/stg-app-fleet-frontend
