apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apex-sync-on-board-refunds
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: prd-apex
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    name: apex-sync-on-board-refunds
    module: apex
    namespace: prd-apex
    replicas: 1
    image:
      repository: ghcr.io/tmlmobilidade/go-apex-sync-on-board-refunds
      tag: staging
      pullPolicy: IfNotPresent
    service:
      port: 80
      targetPort: 5050
    ingress:
      enabled: false
    platformSecrets:
      - prd-platform-storage
    env: []
