apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pr-637-apex-pcgi-sync
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: onepassword-connect
  targetNamespace: pr-637-apex
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    environment: pr-637
    module: apex
    app: pcgi-sync
    replicas: 1
    resources:
      memory: 4Gi
    service:
      targetPort: 5050
    ingress:
      enabled: true
      host: pr-637.go-stg.tmlmobilidade.pt
    secrets:
      - stg-platform-pcgi-file-manager
      - stg-platform-pcgi-tunnel
      - stg-platform-rawdb
    env: []
  suspend: false
