apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - auth-api.yaml
  - auth-cleaner.yaml
  - auth-frontend.yaml
  - auth-secrets.yaml
  - exporter-api.yaml
  - exporter-cleaner.yaml
  - exporter-export-drt.yaml
  - exporter-export-files.yaml
  - exporter-frontend.yaml
  - exporter-secrets.yaml
  - plans-api.yaml
  - plans-export-posters.yaml
  - plans-frontend.yaml
  - plans-organizer.yaml
  - plans-secrets.yaml
  - plans-validator.yaml
