apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apex
  - core
  - controller
  - dates
  - eta
  # - exporter
  - hub
  - locations
  - offer
  - performance
  - operation
  # - infrastructure
  - tracker