apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alerts
  # - apex
  - auth
  - controller
  - dates
  - exporter
  - fleet
  - locations
  # - offer
  # - performance
  - plans
  - stops
  # - tracker
