apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-godb
  namespace: stg-hub
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-godb
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-labdb
  namespace: stg-hub
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-labdb
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-cachedb
  namespace: stg-hub
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-cachedb
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-storage
  namespace: stg-hub
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-storage
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-external-app-secrets
  namespace: stg-hub
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-external-app-secrets
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-sentry
  namespace: stg-hub
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-sentry
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-loki
  namespace: stg-hub
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-loki
