apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - api
  - frontend-navegante-app
  - publish-alerts
  - publish-alerts-cm
  - publish-gtfs
  - publish-gtfs-cm
  - publish-network
  - publish-realtime