###
### THIS FILE IS STILL UNUSED
### DB CREDENTIALS FOR THE BRIDGEDB SHOULD BE ADDED HERE

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-rides-bridge
  namespace: prd-controller
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-app-controller-rides-bridge
