name: valhalla

replicaCount: 1

image:
  repository: ghcr.io/valhalla/valhalla-scripted
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8002

persistence:
  enabled: true
  size: 50Gi
  storageClass: ""
  accessMode: ReadWriteOnce

customFilesPath: /custom_files

pbfUrl: https://download.geofabrik.de/europe/portugal-latest.osm.pbf

env:
  server_threads: "4"
  serve_tiles: "True"
  use_tiles_ignore_pbf: "False"
  tileset_name: valhalla_tiles
  build_elevation: "False"
  build_admins: "False"
  build_time_zones: "False"
  build_transit: "False"
  build_tar: "True"
  force_rebuild: "False"
  update_existing_config: "True"

updateCron:
  enabled: true
  schedule: "0 4 * * *"
  timeZone: Europe/Lisbon

ingress:
  enabled: true
  path: /
  pathType: Prefix
  annotations: {}
  environment: stg