name: valhalla

environment: stg

replicaCount: 1

image:
  repository: ghcr.io/valhalla/valhalla-scripted
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8002

persistence:
  enabled: true
  mountPath: /custom_files
  size: 50Gi
  storageClass: oci-bv
  accessMode: ReadWriteOnce

pbfFileName: portugal-latest.osm.pbf

pbfUrl: https://download.geofabrik.de/europe/portugal-latest.osm.pbf

initDownload:
  enabled: true
  image: curlimages/curl:8.12.1

env:
  server_threads: "4"
  serve_tiles: "True"
  use_tiles_ignore_pbf: "False"
  tileset_name: valhalla_tiles
  build_elevation: "False"
  build_admins: "False"
  build_time_zones: "False"
  build_transit: "False"
  build_tar: "True"
  force_rebuild: "False"
  update_existing_config: "True"

updateCron:
  enabled: true
  schedule: "0 4 * * *"
  timeZone: Europe/Lisbon
  image: bitnami/kubectl:1.31.4
  deploymentName: valhalla

resources: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: true
  path: /
  pathType: Prefix
  annotations: {}
  environment: stg