apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: auth-api-stg
  namespace: auth-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/auth-api-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: auth-cleaner-stg
  namespace: auth-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/auth-cleaner-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: auth-frontend-stg
  namespace: auth-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/auth-frontend-stg
