apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-module-locations
  namespace: stg-locations
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/stg-module-locations
