apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: exporter-api
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: prd-exporter
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    name: exporter-api
    module: exporter
    namespace: prd-exporter
    replicas: 1
    image:
      repository: ghcr.io/tmlmobilidade/go-exporter-api
      tag: staging
      pullPolicy: IfNotPresent
    service:
      port: 80
      targetPort: 5050
    ingress:
      enabled: true
      className: nginx
      host: go-stg.tmlmobilidade.pt
      path: /exporter/api(/|$)(.*)
      pathType: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    secrets:
      - prd-platform-email
      - prd-platform-storage
    env: []
