apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-controller-rides-examiner
  namespace: stg-controller
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/stg-app-controller-rides-examiner
