apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: onepassword
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: onepassword-charts
        namespace: flux-system
      interval: 1h
  values:
    connect:
      create: false
    operator:
      create: true
      authMethod: service-account
      pollingInterval: 900  # seconds (15 minutes)
      autoRestart: true
      serviceAccountToken:
        name: onepassword-service-account-token
        key: token
      watchNamespace:
        - alerts-prd
        - apex-prd
        - auth-prd
        - controller-prd
        - dates-prd
        - exporter-prd
        - fleet-prd
        - locations-prd
        - offer-prd
        - performance-prd
        - plans-prd
        - stops-prd
        - tracker-prd
