apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-environment-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-environment-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-storage-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-storage-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-email-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-email-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-pcgi-legacy-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-pcgi-legacy-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-pcgi-validations-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-pcgi-validations-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-pcgi-ticketing-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-pcgi-ticketing-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-pcgi-file-manager-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-pcgi-file-manager-prd
