apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-environment
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-platform-environment
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-storage
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-platform-storage
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-email
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-platform-email
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-pcgi-legacy
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-platform-pcgi-legacy
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-pcgi-validations
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-platform-pcgi-validations
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-pcgi-ticketing
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-platform-pcgi-ticketing
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-pcgi-file-manager
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-platform-pcgi-file-manager
