apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pr-559-hub-frontend-videowall
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: onepassword-connect
  targetNamespace: pr-559-hub
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    environment: pr-559
    module: hub
    app: frontend-videowall
    replicas: 1
    service:
      targetPort: 3000
    ingress:
      enabled: true
      path: /hub/videowall
      pathType: Prefix
      host: pr-559.go-stg.tmlmobilidade.pt
    secrets:
      - stg-platform-sentry-hub
    env: []
  suspend: false
