apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - alerts-api.yaml
  - alerts-frontend.yaml
  - alerts-organizer.yaml
  - alerts-secrets.yaml
  - auth-api.yaml
  - auth-cleaner.yaml
  - auth-frontend.yaml
  - auth-secrets.yaml
  - controller-api.yaml
  - controller-coordinator.yaml
  - controller-frontend.yaml
  - controller-rides-acceptor.yaml
  - controller-rides-cleaner.yaml
  - controller-rides-examiner.yaml
  - controller-rides-feeder.yaml
  - controller-rides-locker.yaml
  - controller-secrets.yaml
  - dates-api.yaml
  - dates-frontend.yaml
  - dates-secrets.yaml
  - exporter-api.yaml
  - exporter-cleaner.yaml
  - exporter-export-drt.yaml
  - exporter-export-files.yaml
  - exporter-export-posters.yaml
  - exporter-frontend.yaml
  - exporter-secrets.yaml
  - locations-api.yaml
  - locations-frontend.yaml
  - locations-secrets.yaml
  - performance-api.yaml
  - performance-frontend.yaml
  - performance-secrets.yaml
  - performance-sync-metrics-daily.yaml
  - performance-sync-metrics-hourly.yaml
  - performance-sync-metrics-realtime.yaml
  - plans-api.yaml
  - plans-frontend.yaml
  - plans-organizer.yaml
  - plans-secrets.yaml
  - plans-validator.yaml
  - stops-api.yaml
  - stops-frontend.yaml
  - stops-organizer.yaml
  - stops-secrets.yaml
  - stops-tts-cli.yaml
  - stops-tts-server.yaml
  - tracker-es-crtm-aisa-api-fetch.yaml
  - tracker-es-crtm-aisa-rawdb-stream.yaml
  - tracker-es-crtm-la-veloz-api-fetch.yaml
  - tracker-es-crtm-la-veloz-rawdb-stream.yaml
  - tracker-pt-tml-ccfl-api-fetch.yaml
  - tracker-pt-tml-ccfl-rawdb-stream.yaml
  - tracker-pt-tml-cm-alsa-rawdb-stream.yaml
  - tracker-pt-tml-cm-core-stream.yaml
  - tracker-pt-tml-cm-rl-rawdb-stream.yaml
  - tracker-pt-tml-cm-tst-rawdb-stream.yaml
  - tracker-pt-tml-cm-va-rawdb-stream.yaml
  - tracker-pt-tml-cp-api-fetch.yaml
  - tracker-pt-tml-cp-rawdb-stream.yaml
  - tracker-pt-tml-fertagus-api-fetch.yaml
  - tracker-pt-tml-fertagus-rawdb-stream.yaml
  - tracker-pt-tml-ml-api-fetch.yaml
  - tracker-pt-tml-ml-rawdb-stream.yaml
  - tracker-pt-tml-mobi-api-fetch.yaml
  - tracker-pt-tml-mobi-rawdb-stream.yaml
  - tracker-pt-tml-tcb-api-fetch.yaml
  - tracker-pt-tml-tcb-rawdb-stream.yaml
  - tracker-pt-tml-ttsl-api-fetch.yaml
  - tracker-pt-tml-ttsl-rawdb-stream.yaml
  - tracker-pt-tmp-unir-api-fetch.yaml
  - tracker-pt-tmp-unir-ut1-rawdb-stream.yaml
  - tracker-pt-tmp-unir-ut2-rawdb-stream.yaml
  - tracker-pt-tmp-unir-ut3-rawdb-stream.yaml
  - tracker-pt-tmp-unir-ut4-rawdb-stream.yaml
  - tracker-pt-tmp-unir-ut5-rawdb-stream.yaml
  - tracker-secrets.yaml
