apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - apex-organizer.yaml
  - apex-pcgi-stream.yaml
  - apex-pcgi-sync.yaml
  - apex-raw-stream.yaml
  - apex-raw-sync-banking-taps.yaml
  - apex-raw-sync-inspection-decisions.yaml
  - apex-raw-sync-inspections.yaml
  - apex-raw-sync-locations.yaml
  - apex-raw-sync-refunds.yaml
  - apex-raw-sync-sales.yaml
  - apex-raw-sync-validations.yaml
  - apex-secrets.yaml
