apiVersion: v1
kind: Namespace
metadata:
  name: pr-559-apex
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-559-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-559-auth
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-559-dates
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-559-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-559-offer
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-559-controller
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-559-eta
  annotations:
    operator.1password.io/auto-restart: "true"
