apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - auth-api.yaml
  - auth-cleaner.yaml
  - auth-frontend.yaml
  - auth-secrets.yaml
  - stops-api.yaml
  - stops-frontend.yaml
  - stops-organizer.yaml
  - stops-secrets.yaml
