apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.environment }}-{{ .Values.module }}-{{ .Values.app }}"
  namespace: "{{ .Values.environment }}-{{ .Values.module }}"
  labels:
    environment: {{ .Values.environment }}
    module: {{ .Values.module }}
    app: {{ .Values.app }}
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 30s"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      environment: {{ .Values.environment }}
      module: {{ .Values.module }}
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        environment: {{ .Values.environment }}
        module: {{ .Values.module }}
        app: {{ .Values.app }}
    spec:
      containers:
        - name: "{{ .Values.environment }}-{{ .Values.module }}-{{ .Values.app }}"
          image: "ghcr.io/tmlmobilidade/go-{{ .Values.module }}-{{ .Values.app }}:{{ .Values.environment }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.cpu_min | default "0.1" }}
              memory: {{ .Values.resources.memory_min | default "128Mi" }}
            limits:
              cpu: {{ .Values.resources.cpu_max | default 1 }}
              memory: {{ .Values.resources.memory_max | default "512Mi" }}
          {{- if .Values.secrets }}
          envFrom:
            {{- range .Values.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- end }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: HOSTNAME
              value: "0.0.0.0"
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
