apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-tracker-cap-fetch
  namespace: tracker-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-tracker-cap-fetch
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-tracker-ccfl-fetch
  namespace: tracker-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-tracker-ccfl-fetch
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-tracker-clickhouse-stream
  namespace: tracker-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-tracker-clickhouse-stream
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-tracker-clickhouse-sync
  namespace: tracker-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-tracker-clickhouse-sync
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-tracker-cm-stream-core
  namespace: tracker-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-tracker-cm-stream-core
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-tracker-cm-stream-log
  namespace: tracker-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-tracker-cm-stream-log
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-tracker-cm-sync-core
  namespace: tracker-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-tracker-cm-sync-core
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-tracker-cm-sync-log
  namespace: tracker-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-tracker-cm-sync-log
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-tracker-ttsl-fetch
  namespace: tracker-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-tracker-ttsl-fetch
