apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prd-alerts-namespace.yaml
  - prd-apex-namespace.yaml
  - prd-auth-namespace.yaml
  - prd-controller-namespace.yaml
  - prd-dates-namespace.yaml
  - prd-exporter-namespace.yaml
  - prd-fleet-namespace.yaml
  - prd-locations-namespace.yaml
  - prd-offer-namespace.yaml
  - prd-performance-namespace.yaml
  - prd-plans-namespace.yaml
  - prd-stops-namespace.yaml
  - prd-tracker-namespace.yaml
  - ingress-nginx.yaml
  - onepassword-connect.yaml
