apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: onepassword
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: onepassword-charts
        namespace: flux-system
      interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: onepassword-connect
            patch: |
              - op: replace
                path: /spec/template/spec/containers/0/volumeMounts
                value:
                  - name: shared-data
                    mountPath: /home/opuser/.op/data
                  - name: credentials
                    mountPath: /home/opuser/credentials
                    readOnly: true
              - op: replace
                path: /spec/template/spec/containers/0/env
                value:
                  - name: OP_SESSION
                    value: /home/opuser/credentials/1password-credentials.json
                  - name: OP_BUS_PORT
                    value: "11220"
                  - name: OP_BUS_PEERS
                    value: localhost:11221
                  - name: OP_HTTP_PORT
                    value: "8080"
                  - name: OP_LOG_LEVEL
                    value: info
              - op: replace
                path: /spec/template/spec/containers/1/volumeMounts
                value:
                  - name: shared-data
                    mountPath: /home/opuser/.op/data
                  - name: credentials
                    mountPath: /home/opuser/credentials
                    readOnly: true
              - op: replace
                path: /spec/template/spec/containers/1/env
                value:
                  - name: OP_HTTP_PORT
                    value: "8081"
                  - name: OP_SESSION
                    value: /home/opuser/credentials/1password-credentials.json
                  - name: OP_BUS_PORT
                    value: "11221"
                  - name: OP_BUS_PEERS
                    value: localhost:11220
                  - name: OP_LOG_LEVEL
                    value: info
  values:
    connect:
      create: true
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
      api:
        imageRepository: docker.io/1password/connect-api
      sync:
        imageRepository: docker.io/1password/connect-sync
    operator:
      create: true
      authMethod: connect
      imageRepository: docker.io/1password/onepassword-operator
      pollingInterval: 30  # seconds
      autoRestart: true
      token:
        name: onepassword-token
        key: token
      watchNamespace:
        - prd-alerts
        - prd-apex
        - prd-auth
        - prd-controller
        - prd-dates
        - prd-exporter
        - prd-fleet
        - prd-locations
        - prd-offer
        - prd-performance
        - prd-plans
        - prd-stops
        - prd-tracker
