apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-module-apex
  namespace: pr-396-apex
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/stg-module-apex
