apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-module-exporter
  namespace: pr-410-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-module-exporter
