apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-stops-frontend
  namespace: stops-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-stops-frontend
