apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: controller-api
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: prd-controller
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    environment: prd
    module: controller
    app: api
    replicas: 1
    resources:
      cpu: 1
      memory: 1Gi
    service:
      targetPort: 5050
    ingress:
      enabled: true
      path: /controller/api(/|$)(.*)
      pathType: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    secrets:
      - prd-platform-email
      - prd-module-controller
    env: []
