apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-alerts
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-apex
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-auth
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-controller
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-dates
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-locations
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-offer
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-performance
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-plans
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-stops
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-478-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
