apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - module-secrets.1passworditem.yaml
  - platform-secrets.1passworditem.yaml
  - organizer/helmrelease.yaml
  - stream/helmrelease.yaml
  - sync-locations/helmrelease.yaml
  - sync-on-board-refunds/helmrelease.yaml
  - sync-on-board-sales/helmrelease.yaml
  - sync-validations/helmrelease.yaml
