# # #

services:

  postgres:
    image: postgres:latest
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 10gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - /opt/app/persistent-data/data:/var/lib/postgresql/data
    env_file:
      - /opt/app/secrets/.env
    environment:
      PGDATA: /var/lib/postgresql/data