#cloud-config

packages:
  - xfsprogs

runcmd:

  # 1.
  # Configure the firewall to allow Gateway traffic
  # using the script pre-packed by Packer

  - /opt/app/firewall.sh
  - rm /opt/app/firewall.sh

  # 2.
  # Init the Docker compose configuration
  # and run the init-letsencrypt.sh script
  # to obtain SSL certificates for the Gateway

  - cd /opt/app
  - docker compose up -d --build --force-recreate --remove-orphans --pull=always
  - sh init-letsencrypt.sh

final_message: "Gateway configuration complete."
