apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - ccfl-fetch
  - clickhouse-stream
  # - clickhouse-sync
  - cm-stream-core
  # - cm-stream-log
  - cm-sync-core
  # - cm-sync-log
  - cp-fetch
  - mobi-fetch
  - ttsl-fetch
  - tcb-fetch
  - crtm-aisa-fetch
  - fertagus-fetch