apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-clickhouse
  namespace: prd-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-clickhouse
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-pcgi-raw
  namespace: prd-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-pcgi-raw
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-pcgi-legacy
  namespace: prd-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-pcgi-legacy