apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-apex-sync-on-board-sales
  namespace: stg-apex
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-apex-sync-on-board-sales
