apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - api
  - frontend
  - gtfs-validator
  - rides-acceptor
  - rides-cleaner
  - rides-coordinator
  - rides-examiner
  - rides-feeder
  - rides-locker
  - rides-resolver
  # - sams-examiner
  # - sams-feeder