apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-exporter-api
  namespace: exporter-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-exporter-api
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-exporter-cleaner
  namespace: exporter-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-exporter-cleaner
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-exporter-export-drt
  namespace: exporter-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-exporter-export-drt
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-exporter-export-files
  namespace: exporter-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-exporter-export-files
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-exporter-export-gtfs-merged
  namespace: exporter-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-exporter-export-gtfs-merged
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-exporter-export-posters
  namespace: exporter-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-exporter-export-posters
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-exporter-frontend
  namespace: exporter-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-exporter-frontend
