apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-dates-api
  namespace: dates-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-dates-api
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-dates-frontend
  namespace: dates-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-dates-frontend
