apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: alerts-frontend-stg
  namespace: alerts-stg-pr-304
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/alerts-frontend-stg
