apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-stream-stg
  namespace: apex-stg-pr-304
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/apex-stream-stg
