apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: auth-shared-stg
  namespace: auth-stg-pr-304
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/auth-shared-stg
