apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - api/helmrelease.yaml
  - frontend/helmrelease.yaml
  - organizer/helmrelease.yaml
  - tts-cli/helmrelease.yaml
  - tts-server/helmrelease.yaml