apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-organizer-stg
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-organizer-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-stream-stg
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-stream-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-sync-locations-stg
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-sync-locations-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-sync-on-board-refunds-stg
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-sync-on-board-refunds-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-sync-on-board-sales-stg
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-sync-on-board-sales-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-sync-validations-stg
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-sync-validations-stg
