apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-apex-organizer
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-apex-organizer
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-apex-stream
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-apex-stream
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-apex-sync-locations
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-apex-sync-locations
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-apex-sync-on-board-refunds
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-apex-sync-on-board-refunds
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-apex-sync-on-board-sales
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-apex-sync-on-board-sales
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-apex-sync-validations
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-apex-sync-validations
