apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-shared-stg
  namespace: apex-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-shared-stg
