apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-module-fleet
  namespace: pr-404-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-module-fleet
