apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-controller-rides-acceptor
  namespace: prd-controller
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-controller-rides-acceptor
