# # #

volumes:
  certbotdata:

secrets:
  cloudflaretoken:
    file: ./secrets/cloudflare-token.ini

services:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  watchtower:
    image: nickfedor/watchtower
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 1gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=10
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_REMOVE_VOLUMES=TRUE
      - WATCHTOWER_INCLUDE_RESTARTING=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE
      - WATCHTOWER_TIMEOUT=120s
      - WATCHTOWER_ROLLING_RESTART=TRUE

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  certbot:
    image: certbot/dns-cloudflare
    restart: unless-stopped
    mem_limit: 2g
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    secrets:
      - cloudflaretoken
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  nginx:
    image: ghcr.io/tmlmobilidade/go-infra-stg-gateway:main
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 1gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
      - certbotdata:/var/www/certbot:ro
    ports:
      - 80:80
      - 443:443

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  docs:
    image: ghcr.io/tmlmobilidade/go-docs:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 1gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'