apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-tracker-clickhouse-sync
  namespace: tracker-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-tracker-clickhouse-sync
