apiVersion: v1
kind: Namespace
metadata:
  name: pr-624-auth
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-624-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
