apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-organizer-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-organizer-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-stream-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-stream-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-sync-locations-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-sync-locations-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-sync-on-board-refunds-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-sync-on-board-refunds-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-sync-on-board-sales-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-sync-on-board-sales-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: apex-sync-validations-prd
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/apex-sync-validations-prd
