apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-apex-organizer
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-apex-organizer
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-apex-stream
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-apex-stream
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-apex-sync-locations
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-apex-sync-locations
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-apex-sync-on-board-refunds
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-apex-sync-on-board-refunds
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-apex-sync-on-board-sales
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-apex-sync-on-board-sales
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-apex-sync-validations
  namespace: apex-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-apex-sync-validations
