apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pr-633-controller-rides-feeder
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: onepassword-connect
  targetNamespace: pr-633-controller
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    environment: pr-633
    module: controller
    app: rides-feeder
    replicas: 1
    resources:
      memory: 4Gi
    service:
      targetPort: 5050
    ingress:
      enabled: true
      host: pr-633.go-stg.tmlmobilidade.pt
    secrets:
      - stg-module-controller
      - stg-platform-godb
      - stg-platform-storage
    env: []
  suspend: false
