apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-module-exporter
  namespace: pr-633-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-module-exporter
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-godb
  namespace: pr-633-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-godb
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-storage
  namespace: pr-633-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-storage
