apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pr-633-hub-api
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: onepassword-connect
  targetNamespace: pr-633-hub
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    environment: pr-633
    module: hub
    app: api
    replicas: 1
    resources:
      memory: 2Gi
    service:
      targetPort: 5050
    ingress:
      enabled: true
      path: /hub/api(/|$)(.*)
      pathType: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      host: pr-633.go-stg.tmlmobilidade.pt
    secrets:
      - stg-platform-godb
      - stg-platform-cachedb
      - stg-platform-storage
    probes:
      startup:
        enabled: true
    env: []
  suspend: false
