apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: controller-rides-locker
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: stg-controller
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    name: controller-rides-locker
    module: controller
    namespace: stg-controller
    replicas: 1
    image:
      repository: ghcr.io/tmlmobilidade/go-controller-rides-locker
      tag: staging
      pullPolicy: IfNotPresent
    service:
      port: 80
      targetPort: 5050
    ingress:
      enabled: false
    platformSecrets:
      - stg-platform-storage
    env: []
