apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - api/helmrelease.yaml
  - cleaner/helmrelease.yaml
  - frontend/helmrelease.yaml
  - validator/helmrelease.yaml
  - export-posters/helmrelease.yaml
