apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-module-dates
  namespace: prd-dates
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-module-dates
