apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fleet-frontend
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: prd-fleet
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    environment: prd
    module: fleet
    app: frontend
    replicas: 1
    service:
      targetPort: 3000
    ingress:
      enabled: true
      path: /fleet
      pathType: Prefix
    secrets:
      - prd-platform-environment
    env: []
