apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-module-offer
  namespace: offer-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-module-offer
