apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: valhalla
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: tile_urls
              value: {{ .Values.pbfUrl | quote }}
            - name: serve_tiles
              value: "True"
            - name: use_tiles_ignore_pbf
              value: "False"
            - name: build_tar
              value: "True"
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /status
              port: http
            periodSeconds: 30
            failureThreshold: 120
          readinessProbe:
            httpGet:
              path: /status
              port: http
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /status
              port: http
            periodSeconds: 30
            failureThreshold: 6
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
