apiVersion: valhalla.itayankri/v1alpha1
kind: Valhalla
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  pbfUrl: {{ .Values.pbfUrl | quote }}
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  persistence:
    storage: {{ .Values.persistence.storage | quote }}
    accessMode: {{ .Values.persistence.accessMode }}
    {{- with .Values.persistence.storageClassName }}
    storageClassName: {{ . | quote }}
    {{- end }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  service:
    type: {{ .Values.service.type }}
    {{- with .Values.service.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
