apiVersion: v1
kind: Namespace
metadata:
  name: pr-630-auth
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-630-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
