apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - core-api.yaml
  - core-extractions-coordinator.yaml
  - core-extractions-worker.yaml
  - core-frontend.yaml
  - core-organizer.yaml
  - core-secrets.yaml
  - operation-api.yaml
  - operation-frontend.yaml
  - operation-gtfs-validator.yaml
  - operation-organizer.yaml
  - operation-rides-acceptor.yaml
  - operation-rides-coordinator.yaml
  - operation-rides-examiner.yaml
  - operation-rides-feeder.yaml
  - operation-rides-locker.yaml
  - operation-rides-sync.yaml
  - operation-sams-examiner.yaml
  - operation-sams-feeder.yaml
  - operation-secrets.yaml
