apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-module-auth
  namespace: pr-477-auth
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-module-auth
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-storage
  namespace: pr-477-auth
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-storage
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-email
  namespace: pr-477-auth
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-email
