apiVersion: v1
kind: Namespace
metadata:
  name: pr-477-auth
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-477-locations
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-477-stops
  annotations:
    operator.1password.io/auto-restart: "true"
