apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-exporter-export-gtfs-merged
  namespace: stg-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-exporter-export-gtfs-merged
