apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-alerts-api
  namespace: alerts-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-alerts-api
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-alerts-frontend
  namespace: alerts-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-alerts-frontend
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-alerts-organizer
  namespace: alerts-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/stg-app-alerts-organizer
