apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-module-plans
  namespace: prd-plans
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-module-plans
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-go-redis
  namespace: prd-plans
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-go-redis
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-storage
  namespace: prd-plans
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-storage
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-email
  namespace: prd-plans
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-email
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-sentry
  namespace: prd-plans
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-sentry