apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - shared-secrets.1passworditem.yaml
  - platform-secrets.1passworditem.yaml
  - organizer
  - stream
  - sync-locations
  - sync-on-board-refunds
  - sync-on-board-sales
  - sync-validations
