apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-rawdb
  namespace: prd-apex
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-rawdb
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-godb
  namespace: prd-apex
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-godb
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-labdb
  namespace: prd-apex
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-labdb
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-pcgi-tunnel
  namespace: prd-apex
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-pcgi-tunnel
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-pcgi-file-manager
  namespace: prd-apex
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-pcgi-file-manager
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-sentry
  namespace: prd-apex
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-sentry