apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-godb
  namespace: prd-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-godb
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-sentry
  namespace: prd-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-sentry