apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-module-fleet
  namespace: prd-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-module-fleet
