apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pr-620-auth-frontend
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: onepassword-connect
  targetNamespace: pr-620-auth
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    environment: pr-620
    module: auth
    app: frontend
    replicas: 1
    service:
      targetPort: 3000
    ingress:
      enabled: true
      path: /auth
      pathType: Prefix
      host: pr-620.go-stg.tmlmobilidade.pt
    env: []
  suspend: false
