apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-plans-api
  namespace: plans-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-plans-api
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-plans-cleaner
  namespace: plans-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-plans-cleaner
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-plans-frontend
  namespace: plans-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-plans-frontend
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-plans-validator
  namespace: plans-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-plans-validator
