apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pr-397-locations-frontend
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: pr-397-locations
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    module: locations
    replicas: 1
    service:
      targetPort: 3000
    ingress:
      enabled: true
      path: /locations
      pathType: Prefix
      host: pr-397.go-stg.tmlmobilidade.pt
    secrets:
      - stg-platform-email
      - stg-platform-storage
    env: []
    environment: pr-397
    app: frontend
