apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-alerts
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-apex
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-auth
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-controller
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-dates
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-locations
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-offer
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-performance
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-plans
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-stops
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-397-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
