apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-exporter-export-drt
  namespace: stg-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/stg-app-exporter-export-drt
