apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kube-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: alloy
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    controller:
      type: deployment
      replicas: 1
    extraObjects:
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: alloy-pod-logs
        rules:
          - apiGroups: [""]
            resources:
              - pods
              - pods/log
            verbs:
              - get
              - list
              - watch
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: alloy-pod-logs
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: alloy-pod-logs
        subjects:
          - kind: ServiceAccount
            name: kube-system-alloy
            namespace: kube-system
    alloy:
      mounts:
        varlog: false
      resources:
        requests:
          cpu: 2000m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 2Gi
      configMap:
        create: true
        content: |-
          logging {
            level  = "info"
            format = "logfmt"
          }

          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.relabel "pods" {
            targets = discovery.kubernetes.pods.targets

            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_label_app"]
              target_label  = "k8s_app"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
              target_label  = "app"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_instance"]
              target_label  = "instance"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_component"]
              target_label  = "component"
            }
          }

          loki.source.kubernetes "pods" {
            targets    = discovery.relabel.pods.output
            forward_to = [loki.write.default.receiver]
          }

          loki.write "default" {
            endpoint {
              url = "https://grafana.go.tmlmobilidade.pt/loki/api/v1/push"
              batch_wait = "1s"
              remote_timeout = "30s"
            }
            external_labels = {
              cluster = "go-stg",
              environment = "stg",
            }
          }
    configReloader:
      resources:
        requests:
          cpu: 1000m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 1Gi
