apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - stg-alerts-namespace.yaml
  - stg-apex-namespace.yaml
  - stg-auth-namespace.yaml
  - stg-controller-namespace.yaml
  - stg-dates-namespace.yaml
  - stg-exporter-namespace.yaml
  - stg-fleet-namespace.yaml
  - stg-locations-namespace.yaml
  - stg-offer-namespace.yaml
  - stg-performance-namespace.yaml
  - stg-plans-namespace.yaml
  - stg-stops-namespace.yaml
  - stg-tracker-namespace.yaml
  - ingress-nginx.yaml
  - onepassword-connect.yaml
