apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - ingress-nginx.yaml
  - nginx-error-pages
  - onepassword-connect.yaml
  - keel.yaml
  - cert-manager.yaml
  - docs.yaml
# cert-tls/ is applied by Flux Kustomization cert-tls-stg (depends on this platform)
