environment: environment
module: module
app: app

replicas: 1

service:
  targetPort: 5050

resources:
  cpu_min: 0.1
  cpu_max: 1
  memory_min: "128Mi"
  memory_max: "512Mi"

ingress:
  enabled: false
  path: /
  pathType: Prefix
  annotations: {}

secrets: []

env: []
