environment: environment
module: module
app: app

replicas: 1

service:
  targetPort: 5050

resources:
  cpu: 0.1
  memory: "128Mi"

ingress:
  enabled: false
  path: /
  pathType: Prefix
  annotations: {}

secrets: []

env: []
