apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
configMapGenerator:
  - name: nginx-error-pages
    namespace: ingress-nginx
    files:
      - 404.html
      - 500.html
      - 501.html
      - 502.html
      - 503.html
      - 504.html
  - name: nginx-error-pages-conf
    namespace: ingress-nginx
    files:
      - default.conf
generatorOptions:
  disableNameSuffixHash: true
