apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - static-server.yaml
configMapGenerator:
  - name: ingress-nginx-error-pages
    files:
      - 404.html
      - 501.html
      - 502.html
      - 503.html
      - 504.html
generatorOptions:
  disableNameSuffixHash: true
