apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - auth-api.yaml
  - auth-cleaner.yaml
  - auth-frontend.yaml
  - auth-secrets.yaml
  - hub-api.yaml
  - hub-frontend-navegante-app.yaml
  - hub-frontend-videowall.yaml
  - hub-publish-alerts-cm.yaml
  - hub-publish-alerts.yaml
  - hub-publish-gtfs-cm.yaml
  - hub-publish-gtfs.yaml
  - hub-publish-metrics.yaml
  - hub-publish-network.yaml
  - hub-publish-plans.yaml
  - hub-publish-realtime.yaml
  - hub-secrets.yaml
