apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - hub-api.yaml
  - hub-eta.yaml
  - hub-frontend-navegante-app.yaml
  - hub-frontend-videowall.yaml
  - hub-publish-alerts.yaml
  - hub-publish-eta.yaml
  - hub-publish-gtfs-cm.yaml
  - hub-publish-gtfs.yaml
  - hub-publish-metrics.yaml
  - hub-publish-network.yaml
  - hub-publish-plans.yaml
  - hub-publish-vehicles.yaml
  - hub-secrets.yaml
