apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - module-secrets.1passworditem.yaml
  - platform-secrets.1passworditem.yaml
  - api
  - coordinator
  - frontend
  - rides-acceptor
  # - rides-bridge
  - rides-cleaner
  - rides-examiner
  - rides-feeder
  - rides-locker
  # - sams-examiner
  # - sams-feeder