apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tracker-clickhouse-stream
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: stg-tracker
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    module: tracker
    replicas: 1
    service:
      targetPort: 5050
    ingress:
      enabled: false
    secrets:
      - stg-platform-storage
    env: []
    environment: stg
    app: clickhouse-stream
