volumes:
  certbotdata:

secrets:
  cloudflaretoken:
    file: ./secrets/cloudflare.token

services:
  watchtower:
    image: containrrr/watchtower
    mem_limit: 2g
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=10
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE
      - WATCHTOWER_ROLLING_RESTART=TRUE

  nginx:
    image: nginx:alpine-slim
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 1gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cloudflare.conf:/etc/nginx/cloudflare.conf:ro
      - ./letsencrypt:/etc/letsencrypt:ro
      - certbotdata:/var/www/certbot:ro
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 100mb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    secrets:
      - cloudflaretoken
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  planetiler:
    image: ghcr.io/tmlmobilidade/planetiler:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 16gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'

  tileserver:
    image: ghcr.io/tmlmobilidade/tileserver:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'