apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-app-tracker-cm-sync-core
  namespace: stg-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/stg-app-tracker-cm-sync-core
