# # #

services:

  redis:
    image: redis:latest
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 10gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    extra_hosts:
      - "go-prd-cachedb-1.tmlmobilidade.pt:10.81.101.241"
    volumes:
      - /opt/app/persistent-data/data:/data
    environment:
      - REDIS_ARGS=--save 5 1