apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-module-exporter
  namespace: prd-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-module-exporter
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-godb
  namespace: prd-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-godb
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-storage
  namespace: prd-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-storage
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-email
  namespace: prd-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-email
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-platform-sentry
  namespace: prd-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-platform-sentry