apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pr-725-infrastructure-tts-cli
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: onepassword-connect
    - name: infrastructure-tts-server
  targetNamespace: pr-725-infrastructure
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/stg/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    environment: pr-725
    module: infrastructure
    app: tts-cli
    replicas: 1
    resources:
      memory: 4Gi
      cpu: 2000m
    service:
      targetPort: 3000
    ingress:
      enabled: true
      host: pr-725.go-stg.tmlmobilidade.pt
    secrets:
      - stg-module-infrastructure
      - stg-platform-godb
      - stg-platform-storage
    env: []
  suspend: false
