apiVersion: v1
kind: Namespace
metadata:
  name: pr-725-core
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-725-infrastructure
  annotations:
    operator.1password.io/auto-restart: "true"
