apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pr-720-infrastructure-tts-server
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: onepassword-connect
  targetNamespace: pr-720-infrastructure
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/stg/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    environment: pr-720
    module: infrastructure
    app: tts-server
    replicas: 1
    resources:
      memory: 12Gi
      cpu: 4000m
    service:
      targetPort: 8000
    ingress:
      enabled: true
      host: pr-720.go-stg.tmlmobilidade.pt
    secrets:
      - stg-module-infrastructure
      - stg-platform-godb
      - stg-platform-storage
    env: []
  suspend: false
