apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-prd
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-prd
  # How often the kustomization should be reconciled.
  # Keep this moderate to avoid excessive controller churn.
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./compute/kubernetes/modules/prd
  prune: true
