apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - module-secrets.1passworditem.yaml
  - platform-secrets.1passworditem.yaml
  - cap-fetch/helmrelease.yaml
  - ccfl-fetch/helmrelease.yaml
  - clickhouse-stream/helmrelease.yaml
  - clickhouse-sync/helmrelease.yaml
  - cm-stream-core/helmrelease.yaml
  - cm-stream-log/helmrelease.yaml
  - cm-sync-core/helmrelease.yaml
  - cm-sync-log/helmrelease.yaml
  - ttsl-fetch/helmrelease.yaml
