apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-tracker-ttsl-fetch
  namespace: prd-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/prd-app-tracker-ttsl-fetch
