apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: controller-api
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: stg-controller
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    name: controller-api
    module: controller
    namespace: stg-controller
    replicas: 1
    image:
      repository: ghcr.io/tmlmobilidade/go-controller-api
      tag: staging
      pullPolicy: IfNotPresent
    service:
      port: 80
      targetPort: 5050
    ingress:
      enabled: true
      className: nginx
      host: go-stg.tmlmobilidade.pt
      path: /controller/api(/|$)(.*)
      pathType: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    secrets:
      - stg-platform-email
      - stg-platform-storage
    env: []
