apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - shared-secrets.1passworditem.yaml
  - app-secrets.1passworditem.yaml
  - cap-fetch.yaml
  - ccfl-fetch.yaml
  - clickhouse-stream.yaml
  - clickhouse-sync.yaml
  - cm-stream-core.yaml
  - cm-stream-log.yaml
  - cm-sync-core.yaml
  - cm-sync-log.yaml
  - ttsl-fetch.yaml
