apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alerts-frontend
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: onepassword-connect
  targetNamespace: alerts-stg-pr-395
  install:
    createNamespace: true
  chart:
    spec:
      chart: compute/kubernetes/charts/go-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    name: alerts-frontend
    module: alerts
    namespace: alerts-stg-pr-395
    replicas: 1
    image:
      repository: ghcr.io/tmlmobilidade/go-alerts-frontend
      tag: pr-395
      pullPolicy: Always
    service:
      port: 80
      targetPort: 3000
    ingress:
      enabled: true
      className: nginx
      host: pr-395.go-stg.tmlmobilidade.pt
      path: /alerts(/|2211)(.*)
      pathType: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /22112
    secrets:
      - platform-environment-stg
      - platform-email-stg
      - platform-storage-stg
    env: []
