apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-pcgi-validations-stg
  namespace: apex-stg-pr-395
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/platform-pcgi-validations-stg
