apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: auth-api-stg
  namespace: auth-stg-pr-395
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/auth-api-stg
