apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alerts-namespace.yaml
  - alerts-module-shared.1passworditem.yaml
  - alerts-platform-environment.1passworditem.yaml
  - alerts-platform-storage.1passworditem.yaml
  - alerts-platform-email.1passworditem.yaml
  - alerts-platform-pcgi-legacy.1passworditem.yaml
  - alerts-platform-pcgi-validations.1passworditem.yaml
  - alerts-platform-pcgi-ticketing.1passworditem.yaml
  - alerts-platform-pcgi-file-manager.1passworditem.yaml
  - alerts-api.1passworditem.yaml
  - alerts-api.yaml
  - alerts-frontend.1passworditem.yaml
  - alerts-frontend.yaml
  - alerts-organizer.1passworditem.yaml
  - alerts-organizer.yaml
  - apex-namespace.yaml
  - apex-module-shared.1passworditem.yaml
  - apex-platform-environment.1passworditem.yaml
  - apex-platform-storage.1passworditem.yaml
  - apex-platform-email.1passworditem.yaml
  - apex-platform-pcgi-legacy.1passworditem.yaml
  - apex-platform-pcgi-validations.1passworditem.yaml
  - apex-platform-pcgi-ticketing.1passworditem.yaml
  - apex-platform-pcgi-file-manager.1passworditem.yaml
  - apex-organizer.1passworditem.yaml
  - apex-organizer.yaml
  - apex-stream.1passworditem.yaml
  - apex-stream.yaml
  - apex-sync-locations.1passworditem.yaml
  - apex-sync-locations.yaml
  - apex-sync-on-board-refunds.1passworditem.yaml
  - apex-sync-on-board-refunds.yaml
  - apex-sync-on-board-sales.1passworditem.yaml
  - apex-sync-on-board-sales.yaml
  - apex-sync-validations.1passworditem.yaml
  - apex-sync-validations.yaml
  - auth-namespace.yaml
  - auth-module-shared.1passworditem.yaml
  - auth-platform-environment.1passworditem.yaml
  - auth-platform-storage.1passworditem.yaml
  - auth-platform-email.1passworditem.yaml
  - auth-platform-pcgi-legacy.1passworditem.yaml
  - auth-platform-pcgi-validations.1passworditem.yaml
  - auth-platform-pcgi-ticketing.1passworditem.yaml
  - auth-platform-pcgi-file-manager.1passworditem.yaml
  - auth-api.1passworditem.yaml
  - auth-api.yaml
  - auth-cleaner.1passworditem.yaml
  - auth-cleaner.yaml
  - auth-frontend.1passworditem.yaml
  - auth-frontend.yaml
