apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: go-infra
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/tmlmobilidade/go-infra
  ref:
    branch: main
