apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-module-fleet
  namespace: pr-626-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-module-fleet
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-godb
  namespace: pr-626-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-godb
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-labdb
  namespace: pr-626-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-labdb
