apiVersion: v1
kind: Namespace
metadata:
  name: pr-626-auth
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-626-fleet
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-626-stops
  annotations:
    operator.1password.io/auto-restart: "true"
