apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: auth-api-previews
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: tmlmobilidade
          repo: go
          tokenRef:
            secretName: github-token
            key: token
  template:
    metadata:
      name: "auth-api-pr-{{number}}"
      labels:
        app: auth-api
        module: auth
        preview: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/tmlmobilidade/go-infra
        targetRevision: main
        path: kubernetes/charts/auth-api
        helm:
          parameters:
            - name: image.tag
              value: "pr-{{number}}"
            - name: ingress.host
              value: "auth-pr-{{number}}.preview.tmlmobilidade.pt"
            - name: ingress.path
              value: /
            - name: name
              value: "auth-api"
            - name: namespace
              value: "auth-preview-{{number}}"
            - name: replicas
              value: "1"
      destination:
        server: https://kubernetes.default.svc
        namespace: "auth-preview-{{number}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true