apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-module-alerts
  namespace: pr-400-alerts
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/stg-module-alerts
