apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - alerts-module-secrets.1passworditem.yaml
  - alerts-platform-secrets.1passworditem.yaml
  - apex-module-secrets.1passworditem.yaml
  - apex-platform-secrets.1passworditem.yaml
  - auth-module-secrets.1passworditem.yaml
  - auth-platform-secrets.1passworditem.yaml
  - controller-module-secrets.1passworditem.yaml
  - controller-platform-secrets.1passworditem.yaml
  - dates-module-secrets.1passworditem.yaml
  - dates-platform-secrets.1passworditem.yaml
  - exporter-module-secrets.1passworditem.yaml
  - exporter-platform-secrets.1passworditem.yaml
  - fleet-module-secrets.1passworditem.yaml
  - fleet-platform-secrets.1passworditem.yaml
  - locations-module-secrets.1passworditem.yaml
  - locations-platform-secrets.1passworditem.yaml
  - offer-module-secrets.1passworditem.yaml
  - offer-platform-secrets.1passworditem.yaml
  - performance-module-secrets.1passworditem.yaml
  - performance-platform-secrets.1passworditem.yaml
  - plans-module-secrets.1passworditem.yaml
  - plans-platform-secrets.1passworditem.yaml
  - stops-module-secrets.1passworditem.yaml
  - stops-platform-secrets.1passworditem.yaml
  - tracker-module-secrets.1passworditem.yaml
  - tracker-platform-secrets.1passworditem.yaml
  - alerts-api.yaml
  - alerts-frontend.yaml
  - alerts-organizer.yaml
  - apex-organizer.yaml
  - apex-stream.yaml
  - apex-sync-locations.yaml
  - apex-sync-on-board-refunds.yaml
  - apex-sync-on-board-sales.yaml
  - apex-sync-validations.yaml
  - auth-api.yaml
  - auth-cleaner.yaml
  - auth-frontend.yaml
  - controller-api.yaml
  - controller-coordinator.yaml
  - controller-frontend.yaml
  - controller-rides-acceptor.yaml
  - controller-rides-bridge.yaml
  - controller-rides-cleaner.yaml
  - controller-rides-examiner.yaml
  - controller-rides-feeder.yaml
  - controller-rides-locker.yaml
  - controller-sams-examiner.yaml
  - controller-sams-feeder.yaml
  - dates-api.yaml
  - dates-frontend.yaml
  - exporter-api.yaml
  - exporter-cleaner.yaml
  - exporter-export-drt.yaml
  - exporter-export-files.yaml
  - exporter-export-gtfs-merged.yaml
  - exporter-export-posters.yaml
  - exporter-frontend.yaml
  - fleet-api.yaml
  - fleet-frontend.yaml
  - locations-api.yaml
  - locations-frontend.yaml
  - offer-api.yaml
  - offer-frontend.yaml
  - performance-api.yaml
  - performance-frontend.yaml
  - performance-sync-metrics-daily.yaml
  - performance-sync-metrics-hourly.yaml
  - performance-sync-metrics-realtime.yaml
  - plans-api.yaml
  - plans-cleaner.yaml
  - plans-frontend.yaml
  - plans-validator.yaml
  - stops-api.yaml
  - stops-frontend.yaml
  - stops-organizer.yaml
  - tracker-cap-fetch.yaml
  - tracker-ccfl-fetch.yaml
  - tracker-clickhouse-stream.yaml
  - tracker-clickhouse-sync.yaml
  - tracker-cm-stream-core.yaml
  - tracker-cm-stream-log.yaml
  - tracker-cm-sync-core.yaml
  - tracker-cm-sync-log.yaml
  - tracker-ttsl-fetch.yaml
