apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-module-tracker
  namespace: pr-400-tracker
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-module-tracker
