apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-godb
  namespace: pr-648-offer
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-godb
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-storage
  namespace: pr-648-offer
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-storage
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stg-platform-valhalla
  namespace: pr-648-offer
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-stg/items/stg-platform-valhalla