apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: alerts-api-prd
  namespace: alerts-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/alerts-api-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: alerts-frontend-prd
  namespace: alerts-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/alerts-frontend-prd
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: alerts-organizer-prd
  namespace: alerts-prd
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/alerts-organizer-prd
