apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prd-app-exporter-export-files
  namespace: prd-exporter
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/go-prd/items/prd-app-exporter-export-files
