name: 'Gateway | Build & Push'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'compute/gateway/**'
      - '.github/workflows/build-gateway.yml'

# # #

jobs:

  # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # #

  prd-gateway:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          file: ./compute/gateway/prd/nginx/Dockerfile
          tags: ghcr.io/tmlmobilidade/go-infra-prd-gateway:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # #

  stg-gateway:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          file: ./compute/gateway/stg/nginx/Dockerfile
          tags: ghcr.io/tmlmobilidade/go-infra-stg-gateway:${{ github.ref_name }}