apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alerts-stg-namespace.yaml
  - apex-stg-namespace.yaml
  - auth-stg-namespace.yaml
  - platform-secrets-alerts.yaml
  - platform-secrets-apex.yaml
  - platform-secrets-auth.yaml
  - ingress-nginx.yaml
  - onepassword-connect.yaml
