apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-environment-stg
  namespace: alerts-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-environment-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-storage-stg
  namespace: alerts-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-storage-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-email-stg
  namespace: alerts-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-email-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-pcgi-legacy-stg
  namespace: alerts-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-pcgi-legacy-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-pcgi-validations-stg
  namespace: alerts-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-pcgi-validations-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-pcgi-ticketing-stg
  namespace: alerts-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-pcgi-ticketing-stg
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: platform-pcgi-file-manager-stg
  namespace: alerts-stg
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s/items/platform-pcgi-file-manager-stg
