apiVersion: v1
kind: Namespace
metadata:
  name: pr-640-auth
  annotations:
    operator.1password.io/auto-restart: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-640-stops
  annotations:
    operator.1password.io/auto-restart: "true"
